root = "."
tmp_dir ="tmp"
# config for air
[build]
	cmd = "go build -o main"
	bin = "main"
	dir = "."
	include_ext = ["go"]
	exclude_dir = ["vendor"]
	run_after_build = "chmod +x main"

[log]
# non prod setup anyways
	level = "debug"
